// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	installerConfigFieldNames          = builder.RawFieldNames(&InstallerConfig{})
	installerConfigRows                = strings.Join(installerConfigFieldNames, ",")
	installerConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(installerConfigFieldNames, "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	installerConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(installerConfigFieldNames, "`park_env_id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"

	cacheInstallerConfigParkEnvIdPrefix = "cache:installerConfig:parkEnvId:"
)

type (
	installerConfigModel interface {
		Insert(ctx context.Context, data *InstallerConfig) (sql.Result, error)
		FindOne(ctx context.Context, parkEnvId string) (*InstallerConfig, error)
		Update(ctx context.Context, data *InstallerConfig) error
		Delete(ctx context.Context, parkEnvId string) error
	}

	defaultInstallerConfigModel struct {
		sqlc.CachedConn
		table string
	}

	InstallerConfig struct {
		ParkEnvId  string    `db:"park_env_id"`
		ConfUrl    string    `db:"conf_url"`
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newInstallerConfigModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultInstallerConfigModel {
	return &defaultInstallerConfigModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`installer_config`",
	}
}

func (m *defaultInstallerConfigModel) Delete(ctx context.Context, parkEnvId string) error {
	installerConfigParkEnvIdKey := fmt.Sprintf("%s%v", cacheInstallerConfigParkEnvIdPrefix, parkEnvId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `park_env_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, parkEnvId)
	}, installerConfigParkEnvIdKey)
	return err
}

func (m *defaultInstallerConfigModel) FindOne(ctx context.Context, parkEnvId string) (*InstallerConfig, error) {
	installerConfigParkEnvIdKey := fmt.Sprintf("%s%v", cacheInstallerConfigParkEnvIdPrefix, parkEnvId)
	var resp InstallerConfig
	err := m.QueryRowCtx(ctx, &resp, installerConfigParkEnvIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `park_env_id` = ? limit 1", installerConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, parkEnvId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInstallerConfigModel) Insert(ctx context.Context, data *InstallerConfig) (sql.Result, error) {
	installerConfigParkEnvIdKey := fmt.Sprintf("%s%v", cacheInstallerConfigParkEnvIdPrefix, data.ParkEnvId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, installerConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParkEnvId, data.ConfUrl)
	}, installerConfigParkEnvIdKey)
	return ret, err
}

func (m *defaultInstallerConfigModel) Update(ctx context.Context, data *InstallerConfig) error {
	installerConfigParkEnvIdKey := fmt.Sprintf("%s%v", cacheInstallerConfigParkEnvIdPrefix, data.ParkEnvId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `park_env_id` = ?", m.table, installerConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ConfUrl, data.ParkEnvId)
	}, installerConfigParkEnvIdKey)
	return err
}

func (m *defaultInstallerConfigModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheInstallerConfigParkEnvIdPrefix, primary)
}

func (m *defaultInstallerConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `park_env_id` = ? limit 1", installerConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInstallerConfigModel) tableName() string {
	return m.table
}
