// Code generated by goctl. DO NOT EDIT.
package types

type NewGameReq struct {
	GameId         int64  `json:"game_id"`
	GameName       string `json:"game_name"`
	GameNameAbbrev string `json:"game_name_abbrev"`
}

type NewParkEnvReq struct {
	ParkEnvId      string `json:"park_env_id"`
	GameId         int64  `json:"game_id"`
	Name           string `json:"name"`
	UpdateStrategy int64  `json:"update_strategy"`
}

type NewGameReply struct {
	Code   int64  `json:"code"`
	Result string `json:"result"`
}

type NewParkEnvResp struct {
	Code   int64  `json:"code"`
	Result string `json:"result"`
}
