// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"launcher_micro/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/oauth2/aliyunidaas/callback",
				Handler: UserOauthCallbackHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RoleCheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/user/:phone_num",
					Handler: UserHandler(serverCtx),
				},
			}...,
		),
	)
}
