// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	PhoneNum string `json:"phone_num"`
	Password string `json:"password"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserLoginResp struct {
	Idtoken string `json:"id_token"`
	Expire  string `json:"expire"`
}

type UserInfoResp struct {
	Code   int64  `json:"code"`
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Number string `json:"phone_number"`
}
