// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	PhoneNum string `form:"phone_num"`
}

type UserInfoReq struct {
	PhoneNum string `path:"phone_num"`
}

type UserOauthCallBack struct {
	Code  string `form:"code"`
	State string `form:"state"`
}

type UserLoginResp struct {
	Idtoken   string `json:"id_token"`
	ExpiresIn int64  `json:"expires_in"`
	ExpiresAt int64  `json:"expires_at"`
}

type UserInfoResp struct {
	Code   int64  `json:"code"`
	Name   string `json:"name"`
	Number string `json:"phone_number"`
}

type UserOauthCallBackResp struct {
	IdToken   string `json:"id_token"`
	ExpiresIn int64  `json:"expires_in"`
	ExpiresAt int64  `json:"expires_at"`
}
