// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	PhoneNum string `form:"phone_num"`
	Password string `form:"password"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserOauthCallBack struct {
	Code  string `form:"code"`
	State string `form:"state"`
}

type UserLoginResp struct {
	Idtoken string `json:"id_token"`
	Expire  string `json:"expire"`
}

type UserInfoResp struct {
	Code   int64  `json:"code"`
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Number string `json:"phone_number"`
}

type UserOauthCallBackResp struct {
	IdToken   string `json:"id_token"`
	ExpiresIn int64  `json:"expires_in"`
	ExpiresAt int64  `json:"expires_at"`
}
